# Generated by Django 3.1.5 on 2021-01-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='goods',
            field=models.ManyToManyField(blank=True, related_name='order', to='core.Good'),
        ),
    ]
